#!/bin/bash
# Day 5 Test Runbook

cd /h/Huddle1/huddle-to-buy

echo "=== Starting AXL nodes ==="
echo "Run these 4 commands in separate terminals:"
echo ""
echo "Terminal 1 (AXL nodeA):"
echo "  bash axl/scripts/run-node.sh nodeA"
echo ""
echo "Terminal 2 (AXL nodeB):"
echo "  bash axl/scripts/run-node.sh nodeB"
echo ""
echo "Terminal 3 (AXL nodeC):"
echo "  bash axl/scripts/run-node.sh nodeC"
echo ""
echo "Terminal 4 (AXL nodeS - for seller):"
echo "  bash axl/scripts/run-node.sh nodeS"
echo ""
echo "=== Starting agents ==="
echo "After AXL nodes are running, run these in separate terminals:"
echo ""
echo "Terminal 5 (Seller agent):"
echo "  pnpm exec tsx src/index.ts seller"
echo ""
echo "Terminal 6 (Buyer1 - Coordinator):"
echo "  source agent/.env.buyer1 && pnpm exec tsx agent/src/index.ts run"
echo ""
echo "Terminal 7 (Buyer2):"
echo "  source agent/.env.buyer2 && pnpm exec tsx agent/src/index.ts run"
echo ""
echo "Terminal 8 (Buyer3):"
echo "  source agent/.env.buyer3 && pnpm exec tsx agent/src/index.ts run"
echo ""
echo "Expected flow:"
echo "1. Buyers will commit their intents"
echo "2. After K=3 threshold, reveal protocol triggers"
echo "3. Cluster forms with buyer1 as coordinator"
echo "4. Buyer1 sends negotiate_request to seller"
echo "5. Seller responds with offer"
echo "6. Buyer1 calls createCoalition on Gensyn Testnet (SHOULD NOW WORK WITH FIX)"
echo "7. Buyer1 funds coalition"
echo "8. Buyer2 and Buyer3 fund coalition"
echo "9. Seller's keeper calls commit() to initiate order fulfillment"
